version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/retailys
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER_NAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DEBUG=True
      - SECRET_KEY=secret_key
    depends_on:
      - db
